---
- name: This is used to deploy the latest version of Yazz publicly
  hosts: webservers
  vars:
    node_version: 6.1.0
  tasks:

    - name: install the latest version of Git
      yum:
        name: git
        state: latest


    - name: install the latest version of Yazz
      git:
        repo: 'https://github.com/zubairq/pilot.git'
        dest: /root/visifile


    - name: Install wget
      yum:
        name: wget
        state: present
