---
- name: This is used to deploy the latest version of Yazz publicly
  hosts: webservers
  tasks:
    - name: copy a file
      copy:
        src: public/visifile/index.html
        dest: visifile/public/visifile/index.html
