---
- name: This is used to deploy the latest version of Yazz publicly
  hosts: webservers
  tasks:
    - name: reboot Linux server
      reboot:
        reboot_timeout: 120
    - name: install the latest version of Git
      yum:
        name: git
        state: latest
