---
- name: This is used to deploy the latest version of Yazz publicly
  hosts: webservers
  tasks:
    - name: copy a file
      copy:
        content: hello world changed by Ansible Again
        dest: visifile/public/visifile/testfile.txt
