apiVersion: apps/v1
kind: Deployment
metadata:
  name: vjs-deployment
  labels:
    app: vjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vjs
  template:
    metadata:
      labels:
        app: vjs
    spec:
      containers:
      - name: vjs
        image: yazzcom/visualjavascript:2021
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vjs
  name: vjs-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
  selector:
    app: vjs
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
