apiVersion: apps/v1
kind: Deployment
metadata:
  name: appshare-deployment
  labels:
    app: appshare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appshare
  template:
    metadata:
      labels:
        app: appshare
    spec:
      containers:
      - name: appshare
        image: appshareco/appshare:3.1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: appshare
  name: appshare-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
  selector:
    app: appshare
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
