apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-deployment
  labels:
    app: pilot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pilot
  template:
    metadata:
      labels:
        app: pilot
    spec:
      containers:
      - name: pilot
        image: appshareco/appshare:3.0
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pilot
  name: pilot-deployment
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
  selector:
    app: pilot
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
