apiVersion: template.openshift.io/v1
kind: Template
message: Installing yazz
metadata:
  annotations:
    description: yazz16
    iconClass: icon-3scale
    openshift.io/display-name: yazz16
    openshift.io/provider-display-name: Yazz
    tags: integration, api management
  creationTimestamp: null
  name: yazz16




objects:
  - apiVersion: "v1"
    kind: "DeploymentConfig"
    metadata:
      name: "yazz16"
    spec:
      template:
        metadata:
          labels:
            name: "yazz"
        spec:
          containers:
          - name: "yazz"
            image: "zubairq/visualjs:latest"
            ports:
            - containerPort: 3000
              protocol: "TCP"
      replicas: 1
      selector:
        name: "yazz"
  - apiVersion: v1
    kind: Service
    metadata:
      name: visualjs
    spec:
      ports:
        - name: 3000-tcp
          port: 3000
          protocol: TCP
          targetPort: 3000
      selector:
        deploymentconfig: visualjs
