name: yazz
summary: Cloud and Desktop IDE
version: '3.0.10'
description: |
  This is Yazz.
grade: devel
confinement: devmode
apps:
  yazz:
    command: yazz
    plugs: [network, network-bind]
parts:
  yazz:
    plugin: nodejs
    source: .
