name: visualjs
summary: Kubernetes Enterprise App Store
version: git
description: Kubernetes Enterprise App Store
grade: devel
confinement: strict



apps:
  yazz:
    command: node ./src/electron.js --runapp homepage --nogui true --locked false
    plugs: [network, network-bind]
parts:
  yazz:
    plugin: nodejs
    node-packages: []
    node-engine: 7.7.3
    source: .
