name: pilot
base: core18
summary: The self service app builder for Kubernetes
version: git
description: The self service app builder for Kubernetes
grade: devel
confinement: devmode



apps:
  pilot:
    command: node $SNAP/src/electron.js --runapp homepage --locked false
    plugs:
      - network
      - network-bind


parts:
  pilot:
    source: .
    plugin: nodejs
