name: yazz
summary: Cloud and Desktop IDE
version: '3.0.10'
description: |
  This is Yazz.
grade: devel
confinement: devmode



apps:
  yazz:
    command: yazz
    plugs: [network, network-bind]
parts:
  yazz:
    plugin: nodejs
    node-packages: [sqlite3@4.0.2]
    node-engine: 10.15.3
    source: .
