  name: visifile
  version: git
  summary: Desktop search,. Reinvented
  description: |
    This is Visifile.

  grade: devel 
  confinement: devmode

  apps:
    visifile:
      command: visifile
      plugs: [network]
    
  parts:
    visifile:
      plugin: nodejs
      source: .
      npm-run: build
