name: visualjs
base: core18
summary: Kubernetes Enterprise App Store
version: git
description: Kubernetes Enterprise App Store
grade: devel
confinement: strict



apps:
  visualjs:
    command: node ./src/electron.js --runapp homepage --nogui true --locked false
    plugs:
      - network
      - network-bind


parts:
  visualjs:
    node-packages: [sqlite3]
    node-engine: 7.7.3
    source: .
    plugin: nodejs
