  name: visifile
  version: '0.1' 
  summary: Desktop search,. Reinvented
  description: |
    This is Visifile.

  grade: devel 
  confinement: devmode

  apps:
    wethr:
    command: visifile
  parts:
    visifile:
      plugin: nodejs
      source: .
