name: yazz
summary: Cloud and Desktop IDE
version: git
description: This is Yazz.
grade: devel
confinement: devmode



apps:
  yazz:
    command: yazz
    plugs: [network, network-bind]
parts:
  yazz:
    plugin: nodejs
    node-packages: []
    node-engine: 7.7.3
    source: .
