name: visualjs
base: core18
summary: Kubernetes Enterprise App Store
version: git
description: Kubernetes Enterprise App Store
grade: devel
confinement: devmode



apps:
  visualjs:
    command: node $SNAP/src/electron.js --runapp homepage --locked false
    plugs:
      - network
      - network-bind


parts:
  visualjs:
    source: .
    plugin: nodejs
